Repository squid-cache/ci, pull requests merged in 2025-02, with the labels that each got.

#27 Update mk-release-series.sh
  release/mk-release-series.sh
Labels: M-failed-description

#21 Initial backports automation
  maintenance/code-backports.sh
  maintenance/code-maintenance.sh
Labels: M-cleared-for-merge, M-waiting-staging-checks

#29 Update mk-release-series.sh
  release/mk-release-series.sh
Labels: M-waiting-staging-checks
